import { TemplateVariant, CVTemplateId } from "./schemas";

export const TEMPLATE_VARIANTS: TemplateVariant[] = [
  // ── Clean Professional (1-3) ─────────────────────────────────────────
  {
    id: "clean-blue",
    name: "Clean Blue",
    description: "Trustworthy navy + sky palette",
    layout: "single-column",
    colors: {
      primary: "#2563eb", secondary: "#1e40af", accent: "#60a5fa",
      background: "#ffffff", text: "#1e293b", heading: "#0f172a",
      muted: "#64748b", surface: "#f8fafc", border: "#e2e8f0",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "standard", sectionStyle: "standard", skillStyle: "pill",
    spacing: "normal",
  },
  {
    id: "clean-slate",
    name: "Clean Slate",
    description: "Pure monochrome minimal",
    layout: "single-column",
    colors: {
      primary: "#334155", secondary: "#1e293b", accent: "#64748b",
      background: "#ffffff", text: "#334155", heading: "#0f172a",
      muted: "#94a3b8", surface: "#f1f5f9", border: "#e2e8f0",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "minimal", sectionStyle: "ghost", skillStyle: "tag",
    spacing: "spacious",
  },
  {
    id: "clean-teal",
    name: "Clean Teal",
    description: "Crisp teal accents on white",
    layout: "single-column",
    colors: {
      primary: "#0d9488", secondary: "#0f766e", accent: "#2dd4bf",
      background: "#ffffff", text: "#1e293b", heading: "#0f172a",
      muted: "#64748b", surface: "#f0fdfa", border: "#ccfbf1",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "standard", sectionStyle: "standard", skillStyle: "pill",
    spacing: "normal",
  },

  // ── Modern Creative (4-6) ──────────────────────────────────────────
  {
    id: "modern-coral",
    name: "Modern Coral",
    description: "Bold coral with deep navy",
    layout: "single-column",
    colors: {
      primary: "#f43f5e", secondary: "#1e293b", accent: "#fb7185",
      background: "#ffffff", text: "#334155", heading: "#0f172a",
      muted: "#94a3b8", surface: "#fff1f2", border: "#fecdd3",
    },
    fonts: { heading: "Plus Jakarta Sans, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "gradient", sectionStyle: "timeline", skillStyle: "pill",
    spacing: "normal",
  },
  {
    id: "modern-emerald",
    name: "Modern Emerald",
    description: "Luxurious emerald and charcoal",
    layout: "single-column",
    colors: {
      primary: "#059669", secondary: "#1e293b", accent: "#34d399",
      background: "#ffffff", text: "#334155", heading: "#0f172a",
      muted: "#94a3b8", surface: "#ecfdf5", border: "#a7f3d0",
    },
    fonts: { heading: "Plus Jakarta Sans, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "accent-bar", sectionStyle: "card", skillStyle: "grid",
    spacing: "normal",
  },
  {
    id: "modern-violet",
    name: "Modern Violet",
    description: "Creative indigo-to-violet gradient",
    layout: "single-column",
    colors: {
      primary: "#7c3aed", secondary: "#4c1d95", accent: "#a78bfa",
      background: "#ffffff", text: "#334155", heading: "#0f172a",
      muted: "#94a3b8", surface: "#f5f3ff", border: "#ddd6fe",
    },
    fonts: { heading: "Plus Jakarta Sans, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "gradient", sectionStyle: "card", skillStyle: "pill",
    spacing: "spacious",
  },

  // ── Bold Statement (7-9) ─────────────────────────────────────────────────
  {
    id: "bold-crimson",
    name: "Bold Crimson",
    description: "Powerful red with dark backdrop",
    layout: "single-column",
    colors: {
      primary: "#dc2626", secondary: "#7f1d1d", accent: "#ef4444",
      background: "#ffffff", text: "#1f2937", heading: "#111827",
      muted: "#6b7280", surface: "#fef2f2", border: "#fecaca",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "dark", sectionStyle: "bordered", skillStyle: "tag",
    spacing: "normal",
  },
  {
    id: "bold-amber",
    name: "Bold Amber",
    description: "Warm amber and charcoal",
    layout: "single-column",
    colors: {
      primary: "#d97706", secondary: "#451a03", accent: "#f59e0b",
      background: "#ffffff", text: "#1f2937", heading: "#111827",
      muted: "#78716c", surface: "#fffbeb", border: "#fde68a",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "centered", sectionStyle: "timeline", skillStyle: "pill",
    spacing: "normal",
  },
  {
    id: "bold-indigo",
    name: "Bold Indigo",
    description: "Deep indigo impact",
    layout: "two-column",
    colors: {
      primary: "#4338ca", secondary: "#312e81", accent: "#6366f1",
      background: "#ffffff", text: "#1e293b", heading: "#0f172a",
      muted: "#64748b", surface: "#eef2ff", border: "#c7d2fe",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "sidebar", sectionStyle: "standard", skillStyle: "bar",
    spacing: "normal",
  },

  // ── Dark/Tech (10-12) ──────────────────────────────────────────────────
  {
    id: "dark-emerald",
    name: "Dark Emerald",
    description: "Terminal-inspired green on black",
    layout: "single-column",
    colors: {
      primary: "#10b981", secondary: "#064e3b", accent: "#34d399",
      background: "#0a0a0a", text: "#d1d5db", heading: "#f9fafb",
      muted: "#6b7280", surface: "#1a1a1a", border: "#1f2937",
    },
    fonts: { heading: "JetBrains Mono, monospace", body: "JetBrains Mono, monospace" },
    headerStyle: "dark", sectionStyle: "bordered", skillStyle: "tag",
    spacing: "normal",
  },
  {
    id: "dark-cyan",
    name: "Dark Cyan",
    description: "Cyberpunk cyan on dark",
    layout: "single-column",
    colors: {
      primary: "#06b6d4", secondary: "#164e63", accent: "#22d3ee",
      background: "#0f1117", text: "#d1d5db", heading: "#f9fafb",
      muted: "#6b7280", surface: "#1a1d27", border: "#1f2937",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "dark", sectionStyle: "card", skillStyle: "grid",
    spacing: "normal",
  },
  {
    id: "dark-rose",
    name: "Dark Rose",
    description: "Elegant rose gold on dark",
    layout: "single-column",
    colors: {
      primary: "#e11d48", secondary: "#4c0519", accent: "#fb7185",
      background: "#0a0a0a", text: "#d1d5db", heading: "#f9fafb",
      muted: "#6b7280", surface: "#1a1a1a", border: "#1f2937",
    },
    fonts: { heading: "Playfair Display, serif", body: "Inter, sans-serif" },
    headerStyle: "centered", sectionStyle: "ghost", skillStyle: "pill",
    spacing: "spacious",
  },

  // ── Minimal/Neutral (13-15) ────────────────────────────────────────────
  {
    id: "minimal-charcoal",
    name: "Minimal Charcoal",
    description: "Modern dark gray minimal",
    layout: "single-column",
    colors: {
      primary: "#1e293b", secondary: "#0f172a", accent: "#475569",
      background: "#fafafa", text: "#334155", heading: "#0f172a",
      muted: "#94a3b8", surface: "#f1f5f9", border: "#e2e8f0",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "minimal", sectionStyle: "ghost", skillStyle: "tag",
    spacing: "spacious",
  },
  {
    id: "minimal-sand",
    name: "Minimal Sand",
    description: "Warm beige minimal",
    layout: "single-column",
    colors: {
      primary: "#a8a29e", secondary: "#57534e", accent: "#c4b5a5",
      background: "#faf6f1", text: "#44403c", heading: "#292524",
      muted: "#a8a29e", surface: "#f5f0eb", border: "#e7e2dc",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "minimal", sectionStyle: "ghost", skillStyle: "tag",
    spacing: "spacious",
  },
  {
    id: "minimal-ivory",
    name: "Minimal Ivory",
    description: "Ultra-light warm tones",
    layout: "single-column",
    colors: {
      primary: "#d4a373", secondary: "#9c6644", accent: "#e6ccb2",
      background: "#fefcf5", text: "#5c4a3a", heading: "#3e2f22",
      muted: "#b8a99a", surface: "#faf5eb", border: "#ede4d8",
    },
    fonts: { heading: "Lora, serif", body: "Inter, sans-serif" },
    headerStyle: "minimal", sectionStyle: "standard", skillStyle: "pill",
    spacing: "normal",
  },

  // ── Warm/Organic (16-18) ─────────────────────────────────────────────────
  {
    id: "warm-terracotta",
    name: "Warm Terracotta",
    description: "Earthy terracotta and cream",
    layout: "single-column",
    colors: {
      primary: "#b45309", secondary: "#78350f", accent: "#d97706",
      background: "#fdf8f5", text: "#44403c", heading: "#292524",
      muted: "#a8a29e", surface: "#fff7ed", border: "#fed7aa",
    },
    fonts: { heading: "Playfair Display, serif", body: "Inter, sans-serif" },
    headerStyle: "accent-bar", sectionStyle: "timeline", skillStyle: "pill",
    spacing: "normal",
  },
  {
    id: "warm-ochre",
    name: "Warm Ochre",
    description: "Golden ochre and olive",
    layout: "single-column",
    colors: {
      primary: "#ca8a04", secondary: "#713f12", accent: "#eab308",
      background: "#fefce8", text: "#3f3a36", heading: "#292524",
      muted: "#a8a29e", surface: "#fef9c3", border: "#fde047",
    },
    fonts: { heading: "Lora, serif", body: "Inter, sans-serif" },
    headerStyle: "standard", sectionStyle: "card", skillStyle: "pill",
    spacing: "normal",
  },
  {
    id: "warm-rust",
    name: "Warm Rust",
    description: "Deep rust and clay",
    layout: "single-column",
    colors: {
      primary: "#c2410c", secondary: "#7c2d12", accent: "#ea580c",
      background: "#fdf8f5", text: "#44403c", heading: "#1c1917",
      muted: "#a8a29e", surface: "#fff7ed", border: "#fed7aa",
    },
    fonts: { heading: "Plus Jakarta Sans, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "dark", sectionStyle: "bordered", skillStyle: "tag",
    spacing: "compact",
  },

  // ── Luxury/Premium (19-21) ──────────────────────────────────────────────
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    description: "Elegant gold and navy",
    layout: "single-column",
    colors: {
      primary: "#b8860b", secondary: "#1a1a2e", accent: "#ffd700",
      background: "#fefcf3", text: "#333333", heading: "#1a1a2e",
      muted: "#999999", surface: "#faf6eb", border: "#e8dcc8",
    },
    fonts: { heading: "Playfair Display, serif", body: "Lato, sans-serif" },
    headerStyle: "accent-bar", sectionStyle: "bordered", skillStyle: "pill",
    spacing: "normal",
  },
  {
    id: "luxury-plum",
    name: "Luxury Plum",
    description: "Rich plum with gold accents",
    layout: "two-column",
    colors: {
      primary: "#7b2d8e", secondary: "#3b0764", accent: "#c084fc",
      background: "#ffffff", text: "#1e1b4b", heading: "#0f0a3c",
      muted: "#6b7280", surface: "#faf5ff", border: "#e9d5ff",
    },
    fonts: { heading: "Playfair Display, serif", body: "Inter, sans-serif" },
    headerStyle: "sidebar", sectionStyle: "standard", skillStyle: "bar",
    spacing: "normal",
  },
  {
    id: "luxury-navy",
    name: "Luxury Navy",
    description: "Regal navy and champagne",
    layout: "single-column",
    colors: {
      primary: "#1e3a5f", secondary: "#0f1d30", accent: "#c9a96e",
      background: "#ffffff", text: "#334155", heading: "#0c1929",
      muted: "#64748b", surface: "#f8fafc", border: "#d4d4d8",
    },
    fonts: { heading: "Playfair Display, serif", body: "Inter, sans-serif" },
    headerStyle: "dark", sectionStyle: "card", skillStyle: "pill",
    spacing: "normal",
  },

  // ── Tech/Modern (22-24) ──────────────────────────────────────────────────
  {
    id: "tech-cobalt",
    name: "Tech Cobalt",
    description: "Electric blue on white",
    layout: "single-column",
    colors: {
      primary: "#1d4ed8", secondary: "#1e40af", accent: "#3b82f6",
      background: "#ffffff", text: "#1e293b", heading: "#0f172a",
      muted: "#64748b", surface: "#eff6ff", border: "#bfdbfe",
    },
    fonts: { heading: "JetBrains Mono, monospace", body: "Inter, sans-serif" },
    headerStyle: "accent-bar", sectionStyle: "standard", skillStyle: "tag",
    spacing: "compact",
  },
  {
    id: "tech-mint",
    name: "Tech Mint",
    description: "Fresh mint and slate",
    layout: "two-column",
    colors: {
      primary: "#14b8a6", secondary: "#0f766e", accent: "#5eead4",
      background: "#ffffff", text: "#1e293b", heading: "#0f172a",
      muted: "#64748b", surface: "#f0fdfa", border: "#ccfbf1",
    },
    fonts: { heading: "Inter, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "sidebar", sectionStyle: "standard", skillStyle: "bar",
    spacing: "normal",
  },
  {
    id: "tech-steel",
    name: "Tech Steel",
    description: "Industrial steel and orange",
    layout: "single-column",
    colors: {
      primary: "#f97316", secondary: "#1e293b", accent: "#fb923c",
      background: "#ffffff", text: "#1e293b", heading: "#0f172a",
      muted: "#64748b", surface: "#f8fafc", border: "#e2e8f0",
    },
    fonts: { heading: "JetBrains Mono, monospace", body: "Inter, sans-serif" },
    headerStyle: "dark", sectionStyle: "bordered", skillStyle: "tag",
    spacing: "compact",
  },

  // ── Vivid Color (25-27) ──────────────────────────────────────────────────
  {
    id: "vivid-sunset",
    name: "Vivid Sunset",
    description: "Blazing sunset gradient",
    layout: "single-column",
    colors: {
      primary: "#e11d48", secondary: "#9d174d", accent: "#f43f5e",
      background: "#ffffff", text: "#1f2937", heading: "#111827",
      muted: "#6b7280", surface: "#fff1f2", border: "#fecdd3",
    },
    fonts: { heading: "Plus Jakarta Sans, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "gradient", sectionStyle: "timeline", skillStyle: "grid",
    spacing: "normal",
  },
  {
    id: "vivid-ocean",
    name: "Vivid Ocean",
    description: "Deep ocean blues",
    layout: "single-column",
    colors: {
      primary: "#0891b2", secondary: "#164e63", accent: "#22d3ee",
      background: "#ffffff", text: "#1e293b", heading: "#0f172a",
      muted: "#64748b", surface: "#ecfeff", border: "#cffafe",
    },
    fonts: { heading: "Plus Jakarta Sans, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "gradient", sectionStyle: "card", skillStyle: "pill",
    spacing: "spacious",
  },
  {
    id: "vivid-forest",
    name: "Vivid Forest",
    description: "Rich forest greens",
    layout: "single-column",
    colors: {
      primary: "#16a34a", secondary: "#14532d", accent: "#4ade80",
      background: "#ffffff", text: "#1e293b", heading: "#0f172a",
      muted: "#64748b", surface: "#f0fdf4", border: "#bbf7d0",
    },
    fonts: { heading: "Plus Jakarta Sans, sans-serif", body: "Inter, sans-serif" },
    headerStyle: "standard", sectionStyle: "timeline", skillStyle: "grid",
    spacing: "normal",
  },

  // ── Pastel Gentle (28-30) ────────────────────────────────────────────────
  {
    id: "pastel-lavender",
    name: "Pastel Lavender",
    description: "Soft purple tones",
    layout: "single-column",
    colors: {
      primary: "#8b5cf6", secondary: "#5b21b6", accent: "#a78bfa",
      background: "#fcfaff", text: "#374151", heading: "#1f2937",
      muted: "#9ca3af", surface: "#f5f3ff", border: "#ede9fe",
    },
    fonts: { heading: "Lora, serif", body: "Inter, sans-serif" },
    headerStyle: "centered", sectionStyle: "card", skillStyle: "pill",
    spacing: "normal",
  },
  {
    id: "pastel-peach",
    name: "Pastel Peach",
    description: "Warm peachy tones",
    layout: "single-column",
    colors: {
      primary: "#f97316", secondary: "#9a3412", accent: "#fb923c",
      background: "#fefcfb", text: "#374151", heading: "#1f2937",
      muted: "#9ca3af", surface: "#fff7ed", border: "#fed7aa",
    },
    fonts: { heading: "Lora, serif", body: "Inter, sans-serif" },
    headerStyle: "centered", sectionStyle: "timeline", skillStyle: "pill",
    spacing: "normal",
  },
  {
    id: "pastel-sky",
    name: "Pastel Sky",
    description: "Light airy blues",
    layout: "two-column",
    colors: {
      primary: "#0ea5e9", secondary: "#075985", accent: "#38bdf8",
      background: "#ffffff", text: "#1e293b", heading: "#0f172a",
      muted: "#64748b", surface: "#f0f9ff", border: "#e0f2fe",
    },
    fonts: { heading: "Lora, serif", body: "Inter, sans-serif" },
    headerStyle: "sidebar", sectionStyle: "standard", skillStyle: "bar",
    spacing: "normal",
  },
];

export const TEMPLATE_MAP = new Map<CVTemplateId, TemplateVariant>(
  TEMPLATE_VARIANTS.map((t) => [t.id, t])
);
